---
title: angelodidonato.com
timezone: UTC
collections:
  posts:
    title: notes
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/notes/:year/:month/:day/:title"
markdown: kramdown
sass:
    sass_dir: _sass